Repository CombinedArmsGaming/CAFE3, pull requests merged in 2022-01, with the labels that each got.

#84 [Hotfix] Fixed side conditionals
  components/briefing/fn_briefing.sqf
  components/ceasefire/init_component.sqf
  components/downtime/ui_functions/fn_downtimeDead_onLoad.sqf
  components/gravestones/fn_getObituary.sqf
  components/joinInProgress/ui_functions/fn_groupPickerDialog_onCloseDialog.sqf
  components/radios/fn_clientSetLanguages.sqf
  components/radios/fn_setupGroupRadioChannels.sqf
  components/respawnWaves/fn_respawnDialogSupport.sqf
  components/respawnWaves/fn_respawnWave.sqf
  configuration/endings.hpp
  respawnTemplates/parts/tryTeleport.sqf
  respawnTemplates/respawnWaves/onPlayerRespawn.sqf
Labels: bug

#96 [Chore] Update Release GitHub Action
  .github/action/auto_assign_config.yml
  .github/workflows/auto_assign.yaml
  .github/workflows/create_draft_release.yml
Labels: chore

#99 [Add] - Visible framework version
  components/briefing/briefings/ca_briefing_admin.sqf
  components/briefing/briefings/ca_briefing_framework.sqf
  components/briefing/briefings/ca_briefing_player.sqf
  components/briefing/briefings/part_briefing_admin.sqf
  components/briefing/fn_briefing.sqf
  macros.hpp
  version.hpp
Labels: enhancement
