Repository CombinedArmsGaming/CAFE3, pull requests merged in 2023-08, with the labels that each got.

#177 [Refactor] - Respawn Refactor Remake
  components/downtime/customSettings.sqf
  components/downtime/fn_downtimeSpectate.sqf
  components/downtime/macros.hpp
  components/downtime/ui/titles.hpp
  components/downtime/ui/unconsciousTitle.hpp
  components/downtime/ui_macros.hpp
  components/functions.hpp
  components/joinInProgress/functions.hpp
  components/joinInProgress/ui_functions/fn_groupPickerDialog_alignPlayerRadios.sqf
  components/joinInProgress/ui_functions/fn_groupPickerDialog_onCloseDialog.sqf
  components/radio/common/fn_configureUnitRadios.sqf
  components/respawn/fn_doRedeployAction.sqf
  components/respawn/fn_respawnSpectatorTweaks.sqf
  components/respawn/functions.hpp
  components/respawn/macros.hpp
  components/respawn/squad/onPlayerRespawn.sqf
  components/respawn/tickets/onPlayerKilled.sqf
  components/respawn/timed/onPlayerKilledOrRespawned.sqf
  components/respawn/triggeredWave/onPlayerKilled.sqf
  components/respawn/ui/macros.hpp
  components/respawn/ui/spawnPickerDialog.hpp
  components/respawn/ui_functions/fn_addSpectatorDowntimeWidgetEventHandler.sqf
  components/respawn/ui_functions/fn_createSpectatorDowntimeWidget.sqf
  components/respawn/ui_functions/fn_spawnPickerDialog_onCloseDialog.sqf
  components/respawn/ui_functions/fn_spawnPickerDialog_populateDialog.sqf
  components/respawn/ui_functions/fn_spectatorDowntimeWidget_updateLoop.sqf
  components/respawn/ui_functions/fn_tryShowSpawnpointDialog.sqf
  components/respawn/ui_functions/fn_ui_handleKeyDown.sqf
  components/respawn/ui_functions/macros.hpp
  components/respawn/ui_macros.hpp
  components/respawn/wave/onPlayerKilledOrRespawned.sqf
  components/respawn/zen/fn_allowImmediateRespawnLocal.sqf
  configuration/respawn.hpp
  description.ext
  dialogs.hpp
  downtime_macros.hpp
  respawn_macros.hpp
  titles.hpp
  ui_defaults.hpp
Labels: enhancement

#174 [Feature] - Add ACE actions to loadout lockers
  components/gearScript/fn_createLoadoutLocker.sqf
  components/gearScript/zen/fn_zen_createLoadoutLocker.sqf
  description.ext
Labels: enhancement

#178 [Release] Stage 1.6.2 Release
  components/ceasefire/fn_client_ceasefireUI.sqf
  components/downtime/customSettings.sqf
  components/downtime/fn_downtimeSpectate.sqf
  components/downtime/macros.hpp
  components/downtime/ui/titles.hpp
  components/downtime/ui/unconsciousTitle.hpp
  components/downtime/ui_macros.hpp
  components/functions.hpp
  components/gearScript/fn_createLoadoutLocker.sqf
  components/gearScript/zen/fn_zen_createLoadoutLocker.sqf
  components/joinInProgress/functions.hpp
  components/joinInProgress/ui_functions/fn_groupPickerDialog_alignPlayerRadios.sqf
  components/joinInProgress/ui_functions/fn_groupPickerDialog_onCloseDialog.sqf
  components/radio/common/fn_configureUnitRadios.sqf
  components/respawn/fn_doRedeployAction.sqf
  components/respawn/fn_respawnSpectatorTweaks.sqf
  components/respawn/functions.hpp
  components/respawn/macros.hpp
  components/respawn/squad/onPlayerRespawn.sqf
  components/respawn/tickets/onPlayerKilled.sqf
  components/respawn/timed/onPlayerKilledOrRespawned.sqf
  components/respawn/triggeredWave/onPlayerKilled.sqf
  components/respawn/ui/macros.hpp
  components/respawn/ui/spawnPickerDialog.hpp
  components/respawn/ui_functions/fn_addSpectatorDowntimeWidgetEventHandler.sqf
  components/respawn/ui_functions/fn_createSpectatorDowntimeWidget.sqf
  components/respawn/ui_functions/fn_spawnPickerDialog_onCloseDialog.sqf
  components/respawn/ui_functions/fn_spawnPickerDialog_populateDialog.sqf
  components/respawn/ui_functions/fn_spectatorDowntimeWidget_updateLoop.sqf
  components/respawn/ui_functions/fn_tryShowSpawnpointDialog.sqf
  components/respawn/ui_functions/fn_ui_handleKeyDown.sqf
  components/respawn/ui_functions/macros.hpp
  components/respawn/ui_macros.hpp
  components/respawn/wave/onPlayerKilledOrRespawned.sqf
  components/respawn/zen/fn_allowImmediateRespawnLocal.sqf
  configuration/respawn.hpp
  description.ext
  dialogs.hpp
  downtime_macros.hpp
  respawn_macros.hpp
  titles.hpp
  ui_defaults.hpp
  version.hpp
Labels: release

#182 [Fix] Resolve Logistics Vehicle Group-Based Access
  components/logiVehicle/fn_canPlayerUseLogi.sqf
Labels: bug

#179 [Bugfix] - Change 3DEN function recompiling
  description.ext
Labels: enhancement
